"use client";

import { useRef, useState } from "react";
import { Check, Download, FileJson, Loader2, Upload } from "lucide-react";
import { categoryMeta, catalog } from "@/app/data/catalog";
import { applyDetectorImport, detectedCategories, detectorCandidates, initialImportChoices, parseDetectorReport, type DetectorReport, type ImportChoice } from "@/app/lib/detector";
import type { BuildConfig, Part } from "@/app/lib/types";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Checkbox } from "@/components/ui/checkbox";
import { Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";

export function DetectorImport({ build, customParts, onApply, initialOpen = false }: { initialOpen?: boolean; build: BuildConfig; customParts: Part[]; onApply: (build: BuildConfig, customParts: Part[]) => void }) {
  const [open, setOpen] = useState(initialOpen), [report, setReport] = useState<DetectorReport | null>(null), [choices, setChoices] = useState<ImportChoice[]>([]), [busy, setBusy] = useState(false), [error, setError] = useState("");
  const fileInput = useRef<HTMLInputElement>(null), reading = useRef(false);
  const parts = [...catalog, ...customParts];
  async function read(file?: File) {
    if (!file || reading.current) return;
    reading.current = true; setBusy(true); setError(""); setReport(null);
    try {
      if (file.size > 1_000_000) throw Error("Escolha um relatório de até 1 MB.");
      if (!file.name.toLowerCase().endsWith(".json")) throw Error("Selecione upgradepc-config.json. O executável não é um arquivo de configuração.");
      const parsed = parseDetectorReport(await file.text());
      setReport(parsed); setChoices(initialImportChoices(parsed, parts));
    } catch (e) { setError(e instanceof Error ? e.message : "Não foi possível ler o relatório."); }
    finally { reading.current = false; setBusy(false); if (fileInput.current) fileInput.current.value = ""; }
  }
  function change(index: number, patch: Partial<ImportChoice>) { setChoices(current => current.map((c, i) => i === index ? { ...c, ...patch } : c)); }
  const included = choices.filter(c => c.include);
  const includedGpus = report?.components.map((component, index) => ({ component, index })).filter(({ component, index }) => component.category === "gpu" && choices[index]?.include) ?? [];
  const complete = included.length > 0 && included.every(c => c.confirmed && c.name.trim()) && (includedGpus.length <= 1 || includedGpus.some(({ index }) => choices[index].primaryGpu));
  return <><Button variant="outline" className="border-cyan-300/20 bg-cyan-300/5 text-cyan-200" onClick={() => setOpen(true)}><Upload />Importar configuração</Button><Dialog open={open} onOpenChange={value => { if (!busy) setOpen(value); }}><DialogContent className="max-h-[92dvh] overflow-y-auto border-white/10 bg-[#0c1320] text-slate-100 sm:max-w-4xl"><DialogHeader><DialogTitle className="text-2xl">{report ? "Encontramos seu PC" : "Importar com o UpgradePC Detector"}</DialogTitle><DialogDescription className="text-sm leading-6 text-slate-400">{report ? "Revise os nomes, escolha os itens que quer incluir e confirme cada modelo. Nada será salvo automaticamente." : "No Windows, execute o Detector e salve o relatório. Depois escolha ou arraste o arquivo JSON abaixo."}</DialogDescription></DialogHeader>
      <input ref={fileInput} type="file" accept=".json,application/json" className="sr-only" aria-label="Arquivo JSON do UpgradePC Detector" onChange={e => void read(e.target.files?.[0])} />
      {!report ? <div className="space-y-5"><div className="grid gap-3 sm:grid-cols-3">{["Baixe e execute o Detector no Windows", "Detecte o hardware e salve o JSON", "Importe, revise os modelos e aplique"].map((text, i) => <p className="rounded-xl border border-white/10 p-4 text-sm leading-6 text-slate-300" key={text}><span className="mb-2 block font-bold text-cyan-200">{i + 1}.</span>{text}</p>)}</div><Button asChild variant="outline" className="border-white/10 bg-white/5"><a href="/detector" target="_blank" rel="noopener noreferrer"><Download />Baixar Detector para Windows</a></Button><button type="button" disabled={busy} onClick={() => fileInput.current?.click()} onDragOver={e => e.preventDefault()} onDrop={e => { e.preventDefault(); void read(e.dataTransfer.files[0]); }} className="flex w-full flex-col items-center gap-3 rounded-xl border border-dashed border-cyan-300/35 bg-cyan-300/5 p-8 text-center hover:bg-cyan-300/10">{busy ? <Loader2 className="size-7 animate-spin" /> : <FileJson className="size-7 text-cyan-300" />}<span className="font-semibold">{busy ? "Lendo relatório…" : "Escolher ou arrastar upgradepc-config.json"}</span><span className="text-sm text-slate-400">JSON de até 1 MB. A leitura acontece neste navegador.</span></button><p className="text-sm leading-6 text-slate-400">O Detector não envia informações ao site. Apenas as peças escolhidas vão para a edição; a conta é atualizada quando você usa Salvar. Fonte, cooler, gabinete e categorias não importadas permanecem como estão.</p></div> : <div className="space-y-5">
        <div className="rounded-xl border border-cyan-300/20 bg-cyan-300/5 p-4 text-sm leading-6 text-slate-300">Relatório v{report.detectorVersion}{report.scannedAt ? ` · ${new Date(report.scannedAt).toLocaleString("pt-BR")}` : ""}<br />Os grupos abaixo que tiverem itens incluídos substituirão as peças atuais daquela categoria, após você aplicar. As outras categorias, suas anotações e montagens serão preservadas.</div>
        {report.warnings.length > 0 && <details className="rounded-xl border border-amber-300/20 p-4"><summary className="cursor-pointer text-sm font-semibold text-amber-200">Observações da detecção ({report.warnings.length})</summary><ul className="mt-3 space-y-2 text-sm leading-6 text-slate-400">{report.warnings.map((w, i) => <li key={i}>{w}</li>)}</ul></details>}
        {report.components.map((component, index) => {
          const choice = choices[index], candidates = detectorCandidates(component, parts);
          return <section className={`rounded-xl border p-4 ${choice.include ? "border-white/15" : "border-white/5 opacity-60"}`} key={index}><div className="flex items-start gap-3"><Checkbox id={`include-${index}`} checked={choice.include} onCheckedChange={checked => change(index, { include: checked === true })} /><label htmlFor={`include-${index}`} className="min-w-0 flex-1"><span className="text-sm font-semibold text-cyan-200">{categoryMeta[component.category].label}</span><span className="mt-1 block font-semibold">{component.name}</span><span className="mt-1 block text-sm text-slate-400">{component.manufacturer || "Fabricante não identificado"}{component.partNumber ? ` · Part number: ${component.partNumber}` : ""}</span></label></div>{choice.include && <div className="mt-4 space-y-3"><p className="text-sm leading-6 text-slate-400">{Object.entries(component.specs).map(([key, value]) => `${({ capacity: component.category === "memory" ? "GB por módulo" : "GB nominais", modules: "Módulos", speed: "Velocidade informada pelo Windows", memoryType: "Memória", interface: "Interface informada", cores: "Núcleos", threads: "Threads" } as Record<string, string>)[key] ?? key}: ${String(value)}`).join(" · ") || "A detecção trouxe apenas a identificação. Outras especificações continuam desconhecidas."}</p><label className="block text-sm">Nome para seu cadastro<Input className="lab-input mt-2" maxLength={160} value={choice.name} onChange={e => change(index, { name: e.target.value, confirmed: false, target: "detected" })} /></label><div><span id={`match-label-${index}`} className="text-sm">Associar ao catálogo ou manter como detectado</span><Select value={choice.target} onValueChange={value => change(index, { target: value, confirmed: false })}><SelectTrigger className="lab-input mt-2 w-full" aria-labelledby={`match-label-${index}`}><SelectValue /></SelectTrigger><SelectContent className="max-h-72"><SelectItem value="detected">Manter dados detectados (peça pessoal)</SelectItem>{candidates.map(p => <SelectItem key={p.id} value={p.id}>{p.brand} · {p.name}</SelectItem>)}</SelectContent></Select></div>{component.category === "gpu" && <p className="text-sm text-amber-200">Confira fabricante da placa e quantidade de VRAM: o nome do chip não identifica a variante.</p>}{component.category === "memory" && <p className="text-sm text-slate-400">Este item é um módulo físico. Kits com mais de um módulo não são sugeridos para evitar contar a RAM em dobro.</p>}<label className="flex items-start gap-2 rounded-lg bg-white/5 p-3 text-sm leading-6"><Checkbox checked={choice.confirmed} className="mt-1" onCheckedChange={checked => change(index, { confirmed: checked === true })} />{choice.target === "detected" ? "Revisei o nome. Vou manter esta peça com os dados detectados e os campos desconhecidos em aberto." : "Conferi que este é o modelo exato. Vou usar as especificações da ficha selecionada."}</label></div>}</section>;
        })}
        {includedGpus.length > 1 && <section className="rounded-xl border border-cyan-300/20 p-4"><label id="main-gpu-label" className="font-semibold">Qual é a placa de vídeo principal?</label><p className="mt-2 text-sm leading-6 text-slate-400">Os adaptadores incluídos ficam cadastrados. O diagnóstico e a simulação usam o principal como referência.</p><Select value={String(includedGpus.find(({ index }) => choices[index].primaryGpu)?.index ?? "")} onValueChange={value => setChoices(current => current.map((choice, i) => ({ ...choice, primaryGpu: i === Number(value) })))}><SelectTrigger aria-labelledby="main-gpu-label" className="mt-3 w-full"><SelectValue placeholder="Escolha o adaptador principal" /></SelectTrigger><SelectContent>{includedGpus.map(({ component, index }) => <SelectItem key={index} value={String(index)}>{choices[index].name || component.name}</SelectItem>)}</SelectContent></Select></section>}
        <section className="rounded-xl border border-white/10 p-4"><h3 className="font-semibold">O que muda na configuração</h3><div className="mt-3 space-y-2 text-sm text-slate-400">{detectedCategories.map(category => { const count = report.components.filter((c, i) => c.category === category && choices[i].include).length; return <p key={category}>{categoryMeta[category].label}: {count ? `${build.parts[category]?.length ?? 0} item(ns) atuais → ${count} importado(s)` : "manter como está"}</p>; })}<p className="text-cyan-200">Fonte, cooler e gabinete: manter como estão.</p></div></section>
      </div>}
      {error && <p className="rounded-lg border border-rose-300/25 p-3 text-sm text-rose-200" role="alert">{error}</p>}
      <DialogFooter className="gap-2">{report && <Button variant="ghost" onClick={() => { setReport(null); setChoices([]); setError(""); }}>Escolher outro arquivo</Button>}<Button variant="outline" disabled={busy} onClick={() => setOpen(false)}>Cancelar</Button>{report && <Button className="bg-cyan-300 text-slate-950 hover:bg-cyan-200" disabled={!complete || busy} onClick={() => { try { const result = applyDetectorImport(build, customParts, report, choices, catalog); onApply(result.build, result.customParts); setOpen(false); setReport(null); setChoices([]); } catch (e) { setError(e instanceof Error ? e.message : "Falha na importação."); } }}><Check />Aplicar à edição</Button>}</DialogFooter>
    </DialogContent></Dialog></>;
}
