"use client";

import { useMemo, useState } from "react";
import { ArrowRight, ArrowRightLeft, Boxes, Check, CircleAlert, CircleCheck, CircleHelp, Clock3, Cpu, Download, FlaskConical, Gauge, HardDrive, History, MemoryStick, Monitor, Pencil, Plus, Power, Search, ShieldCheck, Thermometer, Trash2, X, type LucideIcon } from "lucide-react";
import { toast } from "sonner";
import { DetectorImport } from "@/app/detector-import";
import { categoryMeta, defaultCurrentBuild } from "@/app/data/catalog";
import { compareMetrics } from "@/app/data/glossary";
import { formatSpecValue, getBuildParts } from "@/app/lib/compatibility";
import { changePcPart, changedCategories, diagnosePc, multipleSlots, type PcCheck } from "@/app/lib/my-pc";
import { partCategories, type BuildConfig, type Part, type PartCategory, type PcHistoryEntry } from "@/app/lib/types";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { Sheet, SheetClose, SheetContent, SheetDescription, SheetHeader, SheetTitle } from "@/components/ui/sheet";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";

const icons: Record<PartCategory, LucideIcon> = { cpu: Cpu, motherboard: Boxes, gpu: Gauge, memory: MemoryStick, storage: HardDrive, psu: Power, cooler: Thermometer, case: Boxes, monitor: Monitor };
const primary = "bg-cyan-300 text-slate-950 hover:bg-cyan-200";
const secondary = "border-white/10 bg-white/[0.035] hover:bg-white/10";
const date = (value: string) => new Date(value).toLocaleString("pt-BR", { dateStyle: "short", timeStyle: "short" });
type Picker = { category: PartCategory; index: number; simulation: boolean };

export function MyPcView({ build, parts, history, savedAt, dirty, onChange, onTerm, onExport, onCustom, onContinue, onImport, customParts, initialSimulation, initialImport = false }: {
  customParts: Part[]; onImport: (build: BuildConfig, customParts: Part[]) => void; initialSimulation?: { partId: string; slot: number }; initialImport?: boolean;
  build: BuildConfig; parts: Part[]; history: PcHistoryEntry[]; savedAt: string | null; dirty: boolean;
  onChange: (build: BuildConfig) => void; onTerm: (id: string) => void; onExport: () => void;
  onCustom: (category: PartCategory, index: number) => void; onContinue: (build: BuildConfig) => void;
}) {
  const requestedPart = parts.find(p => p.id === initialSimulation?.partId);
  const requestedSlot = requestedPart ? Math.min(initialSimulation?.slot ?? 0, build.parts[requestedPart.category]?.length ?? 0) : 0;
  const [tab, setTab] = useState(requestedPart ? "simulation" : "configuration");
  const [picker, setPicker] = useState<Picker | null>(null);
  const [details, setDetails] = useState<BuildConfig | null>(null);
  const [simulation, setSimulation] = useState<BuildConfig | null>(() => requestedPart ? changePcPart(build, requestedPart.category, requestedSlot, requestedPart.id) : null);
  const [baseline, setBaseline] = useState<BuildConfig | null>(() => requestedPart ? structuredClone(build) : null);
  const [confirmation, setConfirmation] = useState<{ title: string; detail: string; action: () => void } | null>(null);
  const checks = useMemo(() => diagnosePc(build, parts), [build, parts]);
  const attention = checks.filter(c => c.status === "attention").length;
  const pending = checks.filter(c => c.status === "pending").length;
  const filled = partCategories.filter(c => build.parts[c]?.length).length;
  const ram = getBuildParts(build, "memory", parts);
  const ramKnown = ram.length > 0 && ram.length === (build.parts.memory?.length ?? 0) && ram.every(p => typeof p.specs.capacity === "number" && p.specs.capacity > 0);
  const ramTotal = ram.reduce((sum, p) => sum + (typeof p.specs.capacity === "number" ? p.specs.capacity : 0), 0);
  const cpu = getBuildParts(build, "cpu", parts)[0];
  const gpu = getBuildParts(build, "gpu", parts)[0];
  const simulationChanged = simulation && baseline ? changedCategories(baseline, simulation) : [];
  const simulationStale = baseline && JSON.stringify(build) !== JSON.stringify(baseline);
  function startSimulation() { setBaseline(structuredClone(build)); setSimulation(structuredClone(build)); setTab("simulation"); }
  function selectPart(part: Part) {
    if (!picker) return;
    if (picker.simulation && simulation) setSimulation(changePcPart(simulation, picker.category, picker.index, part.id));
    else onChange(changePcPart(build, picker.category, picker.index, part.id));
    setPicker(null);
  }
  function askRemove(target: BuildConfig, category: PartCategory, index: number, simulated: boolean) {
    if (simulated) { setSimulation(changePcPart(target, category, index, null)); return; }
    setConfirmation({ title: "Remover esta peça?", detail: "Ela será removida da configuração em edição. A alteração só fica na sua conta depois de salvar.", action: () => onChange(changePcPart(target, category, index, null)) });
  }
  function equipment(target: BuildConfig, simulated = false) {
    return <div className="divide-y divide-white/8">{partCategories.map(category => {
      const Icon = icons[category];
      const ids = target.parts[category] ?? [];
      return <section key={category} className="px-4 py-5 sm:px-6">
        <div className="mb-3 flex items-center gap-3"><Icon className="size-4 text-cyan-300" /><h3 className="flex-1 text-sm font-semibold text-slate-300">{categoryMeta[category].label}</h3>{multipleSlots(category) && ids.length > 0 && <Button variant="ghost" size="sm" onClick={() => setPicker({ category, index: ids.length, simulation: simulated })}><Plus />Adicionar</Button>}</div>
        {ids.length ? <div className="space-y-3">{ids.map((id, index) => {
          const part = parts.find(p => p.id === id && p.category === category);
          return <div key={`${id}-${index}`} className="flex flex-wrap items-center gap-3 sm:pl-7"><div className="min-w-0 flex-1 basis-40"><div className="font-semibold text-slate-100">{part?.name ?? "Modelo indisponível no catálogo"}</div><div className="mt-1 text-sm text-slate-400">{part ? compareMetrics[category].filter(metric => part.specs[metric.key] !== undefined).slice(0, 3).map(metric => `${metric.label}: ${formatSpecValue(part.specs[metric.key], metric.unit)}`).join(" · ") || "Especificações não informadas" : `Identificador preservado: ${id}`}</div></div><Button size="sm" variant="outline" className={secondary} onClick={() => setPicker({ category, index, simulation: simulated })} aria-label={`${simulated ? "Simular troca de" : "Alterar"} ${part?.name ?? categoryMeta[category].label}`}><ArrowRightLeft />{simulated ? "Trocar" : "Alterar"}</Button><Button size="icon" variant="ghost" className="text-slate-500 hover:text-rose-300" aria-label={`Remover ${part?.name ?? categoryMeta[category].label}`} onClick={() => askRemove(target, category, index, simulated)}><Trash2 className="size-4" /></Button></div>;
        })}</div> : <button onClick={() => setPicker({ category, index: 0, simulation: simulated })} className="flex w-full items-center gap-2 rounded-lg border border-dashed border-white/15 px-4 py-3 text-left text-sm text-slate-400 transition hover:border-cyan-300/40 hover:text-cyan-200"><Plus className="size-4" />{category === "gpu" && cpu?.specs.igpu === true ? "Vídeo integrado disponível · adicionar GPU dedicada" : `Adicionar ${categoryMeta[category].label.toLowerCase()}`}</button>}
      </section>;
    })}</div>;
  }

  return <div className="space-y-6">
    <div className="flex flex-wrap items-center justify-between gap-3"><p className="text-sm text-slate-400">Cadastre manualmente ou traga os dados do Windows.</p><DetectorImport initialOpen={initialImport} build={build} customParts={customParts} onApply={onImport} /></div>
    <section className="grid gap-5 xl:grid-cols-[minmax(0,1fr)_340px]">
      <div className="lab-panel relative overflow-hidden p-5 sm:p-7">
        <div className="mb-5 flex flex-wrap items-center gap-2 text-sm"><span className="rounded-full border border-cyan-300/20 bg-cyan-300/10 px-3 py-1 text-cyan-200">Meu espaço</span>{build.isExample && <span className="rounded-full border border-amber-300/25 px-3 py-1 text-amber-200">Configuração de exemplo</span>}<span className="ml-auto text-slate-400">{filled}/9 categorias</span></div>
        <div className="flex items-start gap-4"><div className="hidden size-16 shrink-0 place-items-center rounded-2xl border border-cyan-300/20 bg-cyan-300/5 sm:grid"><Monitor className="size-8 text-cyan-200" /></div><div className="min-w-0 flex-1"><h2 className="break-words text-2xl font-bold tracking-tight sm:text-3xl">{build.name || "Meu PC"}</h2><p className="mt-2 text-sm leading-6 text-slate-400">{build.goal === "games" ? "Jogos" : build.goal === "work" ? "Trabalho e criação" : "Uso equilibrado"}{build.applications ? ` · ${build.applications}` : " · Conte como você usa este computador"}</p></div><Button size="icon" variant="ghost" aria-label="Editar nome e uso do PC" onClick={() => setDetails(structuredClone(build))}><Pencil className="size-4" /></Button></div>
        <div className="mt-6 grid gap-4 border-t border-white/10 pt-5 sm:grid-cols-3">{[["PROCESSADOR", cpu?.name ?? "Não informado"], ["VÍDEO", gpu?.name ?? (cpu?.specs.igpu === true ? "Integrado à CPU" : "Não informado")], ["MEMÓRIA", ramKnown ? `${ramTotal} GB no total` : "A completar"]].map(([label, value]) => <div key={label}><div className="text-xs font-semibold tracking-wider text-slate-500">{label}</div><div className="mt-1.5 text-sm font-semibold">{value}</div></div>)}</div>
        <p className="mt-5 flex items-center gap-2 text-sm text-slate-400" role="status"><Clock3 className="size-4" />{dirty ? "Alterações nesta página · salve para guardar na conta" : savedAt ? `Último salvamento: ${date(savedAt)}` : "Pronto para cadastrar seu primeiro PC"}</p>
      </div>
      <div className="lab-panel flex flex-col p-5 sm:p-6"><div className="flex items-center gap-2 text-sm font-semibold text-cyan-200"><ShieldCheck className="size-5" />Verificações da configuração</div><div className="mt-4 text-2xl font-bold">{!filled ? "Vamos conhecer seu PC" : attention ? `${attention} ponto${attention > 1 ? "s" : ""} de atenção` : "Nenhum conflito identificado"}</div><p className="mt-2 text-sm leading-6 text-slate-400">{!filled ? "Adicione suas peças para conferir encaixes e planejar as próximas trocas." : `${pending} verificações pendentes. O diagnóstico usa as fichas cadastradas, sem medir temperatura ou desempenho real.`}</p><Button variant="outline" className={`mt-auto w-full ${secondary}`} onClick={() => setTab("diagnostic")}>Ver diagnóstico<ArrowRight /></Button></div>
    </section>

    <Tabs value={tab} onValueChange={setTab} className="gap-5">
      <div className="overflow-x-auto pb-1"><TabsList variant="line" className="h-12 min-w-max gap-3 border-b border-white/10"><TabsTrigger value="configuration" className="px-3 text-sm"><Cpu />Configuração</TabsTrigger><TabsTrigger value="diagnostic" className="px-3 text-sm"><ShieldCheck />Diagnóstico</TabsTrigger><TabsTrigger value="simulation" className="px-3 text-sm"><FlaskConical />Simular troca</TabsTrigger><TabsTrigger value="history" className="px-3 text-sm"><History />Histórico</TabsTrigger></TabsList></div>

      <TabsContent value="configuration" className="space-y-5">
        {!filled && <div className="rounded-2xl border border-cyan-300/20 bg-cyan-300/5 p-5 sm:p-6"><h3 className="text-xl font-bold">Seu PC começa com a primeira peça</h3><p className="mt-2 max-w-2xl text-slate-400">Selecione o que você já tem. Você pode deixar campos em aberto, incluir mais de um SSD, monitor ou kit de RAM e voltar depois.</p><div className="mt-5 flex flex-wrap gap-3"><Button className={primary} onClick={() => setPicker({ category: "cpu", index: 0, simulation: false })}><Plus />Cadastrar meu processador</Button><Button variant="outline" className={secondary} onClick={() => { onChange({ ...structuredClone(defaultCurrentBuild), id: "example-pc", name: "PC de exemplo", isExample: true, notes: "Configuração demonstrativa. Substitua pelas suas peças." }); toast.info("Exemplo carregado para explorar. Ele está identificado como demonstrativo."); }}>Explorar um exemplo</Button></div></div>}
        <div className="grid items-start gap-5 xl:grid-cols-[minmax(0,1fr)_300px]">
          <section className="lab-panel overflow-hidden"><div className="flex items-center justify-between gap-3 border-b border-white/10 p-5 sm:px-6"><div><h3 className="text-lg font-bold">Peças instaladas</h3><p className="mt-1 text-sm text-slate-400">A base para cada decisão de upgrade.</p></div><Button size="sm" variant="ghost" onClick={onExport}><Download /><span className="hidden sm:inline">Exportar</span></Button></div>{equipment(build)}</section>
          <aside className="space-y-5"><div className="lab-panel p-5"><FlaskConical className="size-6 text-violet-300" /><h3 className="mt-3 text-lg font-bold">E se eu trocar uma peça?</h3><p className="mt-2 text-sm leading-6 text-slate-400">Crie uma simulação com base neste PC e confira o que muda antes de aplicar.</p><Button className={`mt-4 w-full ${secondary}`} variant="outline" disabled={!filled} onClick={() => { if (simulation) setTab("simulation"); else startSimulation(); }}>Simular um upgrade<ArrowRight /></Button></div><div className="lab-panel p-5"><h3 className="font-semibold">Uso e observações</h3><p className="mt-3 whitespace-pre-wrap break-words text-sm leading-6 text-slate-400">{build.notes || "Registre seus programas, necessidades e detalhes que quer lembrar."}</p><Button variant="ghost" className="mt-3 px-0 text-cyan-200" onClick={() => setDetails(structuredClone(build))}><Pencil />Editar informações</Button></div><p className="px-2 text-sm leading-6 text-slate-500">Sua configuração e seu histórico ficam vinculados à sua conta. O catálogo público não mostra seus dados.</p></aside>
        </div>
      </TabsContent>

      <TabsContent value="diagnostic" className="space-y-5"><div><h3 className="text-xl font-bold">Entenda as verificações</h3><p className="mt-2 max-w-3xl text-sm leading-6 text-slate-400">São verificações de especificações, não um teste físico do computador. “Confere” se refere apenas ao item descrito. BIOS, revisões e informações ainda ausentes precisam ser conferidas.</p></div><CheckList checks={checks} onTerm={onTerm} /></TabsContent>

      <TabsContent value="simulation" className="space-y-5">
        {!simulation ? <div className="lab-panel p-6 sm:p-10"><FlaskConical className="size-9 text-violet-300" /><h3 className="mt-5 text-2xl font-bold">Experimente antes de mudar</h3><p className="mt-3 max-w-xl leading-7 text-slate-400">A simulação cria uma cópia da configuração em edição. Troque uma ou várias peças e revise a compatibilidade. Você decide se quer aplicar depois.</p><Button className={`mt-6 ${primary}`} disabled={!filled} onClick={startSimulation}>Iniciar simulação<ArrowRight /></Button>{!filled && <p className="mt-3 text-sm text-slate-400">Cadastre pelo menos uma peça para começar.</p>}</div> : <>
          <div className="rounded-2xl border border-violet-300/25 bg-violet-300/5 p-5"><div className="flex flex-wrap items-start justify-between gap-4"><div><p className="text-sm font-semibold text-violet-200">SIMULAÇÃO · NÃO SALVA</p><h3 className="mt-2 text-xl font-bold">{simulationChanged.length ? `${simulationChanged.length} categoria(s) com alterações` : "Escolha as peças que você quer trocar"}</h3><p className="mt-2 text-sm text-slate-400">Seu PC atual permanece como está. Aplicar carrega as trocas na edição; depois, use Salvar.</p></div><Button variant="ghost" onClick={() => setConfirmation({ title: "Descartar esta simulação?", detail: "As trocas simuladas serão descartadas. Seu PC em edição permanece como está.", action: () => { setSimulation(null); setBaseline(null); } })}><X />Descartar</Button></div>
            {simulationStale && <p className="mt-4 rounded-lg border border-amber-300/30 p-3 text-sm text-amber-200">A configuração mudou desde o início da simulação. Reinicie para usar as peças atuais. <button className="font-semibold underline" onClick={() => setConfirmation({ title: "Reiniciar simulação?", detail: "As trocas simuladas serão substituídas por uma nova cópia da configuração em edição.", action: startSimulation })}>Reiniciar</button></p>}
            {!!simulationChanged.length && <div className="mt-4 space-y-2">{simulationChanged.map(category => <div key={category} className="rounded-lg bg-black/20 p-3 text-sm"><b>{categoryMeta[category].label}</b><div className="mt-1 text-slate-400">{names(baseline!, category, parts)} <span className="text-violet-200">→</span> <span className="text-slate-200">{names(simulation, category, parts)}</span></div></div>)}</div>}
            <div className="mt-4 flex flex-wrap gap-3"><Button className={primary} disabled={!simulationChanged.length || !!simulationStale} onClick={() => { onChange({ ...simulation, name: build.name, id: build.id }); setSimulation(null); setBaseline(null); setTab("configuration"); toast.success("Trocas aplicadas à edição. Salve para guardar na conta."); }}><Check />Aplicar ao Meu PC</Button><Button variant="outline" className={secondary} disabled={!!simulationStale} onClick={() => onContinue({ ...structuredClone(simulation), id: `draft-${Date.now()}`, name: `${build.name} · simulação` })}>Continuar no montador<ArrowRight /></Button></div>
          </div><div className="grid items-start gap-5 xl:grid-cols-2"><section className="lab-panel overflow-hidden"><h3 className="border-b border-white/10 p-5 text-lg font-bold">Peças da simulação</h3>{equipment(simulation, true)}</section><div><h3 className="mb-4 text-lg font-bold">Verificações após as trocas</h3><CheckList checks={diagnosePc(simulation, parts)} onTerm={onTerm} compact /></div></div>
        </>}
      </TabsContent>

      <TabsContent value="history" className="space-y-5"><div><h3 className="text-xl font-bold">A evolução do seu PC</h3><p className="mt-2 text-sm leading-6 text-slate-400">As últimas 30 versões aparecem aqui. Uma versão é criada quando você salva uma mudança no Meu PC. Restaurar carrega a versão na edição; salve para confirmar.</p></div>{!history.length ? <div className="lab-panel p-8 text-center"><History className="mx-auto size-8 text-slate-500" /><h4 className="mt-4 text-lg font-bold">O primeiro capítulo começa ao salvar</h4><p className="mt-2 text-sm text-slate-400">Seu PC atual continua disponível na aba Configuração.</p></div> : <div className="space-y-3">{history.map((entry, index) => <article key={entry.id} className="lab-panel p-5"><div className="flex flex-wrap items-center justify-between gap-4"><div><div className="flex items-center gap-2"><h4 className="font-bold">{entry.build.name || "Meu PC"}</h4>{index === 0 && <span className="rounded bg-cyan-300/10 px-2 py-1 text-xs text-cyan-200">Mais recente</span>}</div><p className="mt-1 text-sm text-slate-400">{date(entry.createdAt)}{entry.build.isExample ? " · exemplo" : ""}</p></div><Button variant="outline" className={secondary} onClick={() => setConfirmation({ title: "Carregar esta versão?", detail: "Ela substituirá a configuração em edição, incluindo alterações ainda não salvas. O histórico será preservado. Salve depois para confirmar a restauração.", action: () => { onChange(structuredClone(entry.build)); setTab("configuration"); toast.info("Versão carregada na edição. Salve para confirmar."); } })}><History />Restaurar</Button></div><details className="mt-4 text-sm"><summary className="cursor-pointer text-cyan-200">Ver peças desta versão</summary><dl className="mt-3 grid gap-3 sm:grid-cols-2">{partCategories.filter(c => entry.build.parts[c]?.length).map(category => <div key={category}><dt className="text-slate-500">{categoryMeta[category].label}</dt><dd className="mt-1 text-slate-200">{names(entry.build, category, parts)}</dd></div>)}</dl>{!Object.values(entry.build.parts).some(ids => ids?.length) && <p className="mt-3 text-slate-400">Nenhuma peça cadastrada nesta versão.</p>}</details></article>)}</div>}</TabsContent>
    </Tabs>

    <PartPicker picker={picker} parts={parts} selected={picker ? (picker.simulation ? simulation : build)?.parts[picker.category]?.[picker.index] : undefined} onClose={() => setPicker(null)} onSelect={selectPart} onTerm={onTerm} onCustom={() => { if (picker && !picker.simulation) { onCustom(picker.category, picker.index); setPicker(null); } }} />
    <Dialog open={!!details} onOpenChange={open => !open && setDetails(null)}><DialogContent className="max-h-[90dvh] overflow-y-auto border-white/10 bg-[#0c1320] text-slate-100"><DialogHeader><DialogTitle>Sobre este computador</DialogTitle><DialogDescription>Esses detalhes ficam junto da sua configuração.</DialogDescription></DialogHeader>{details && <div className="space-y-4"><label className="block text-sm">Nome do PC<Input className="lab-input mt-2" value={details.name} maxLength={100} onChange={e => setDetails({ ...details, name: e.target.value })} /></label><div><label id="pc-goal" className="text-sm">Uso principal</label><Select value={details.goal} onValueChange={value => setDetails({ ...details, goal: value as BuildConfig["goal"] })}><SelectTrigger aria-labelledby="pc-goal" className="lab-input mt-2 w-full"><SelectValue /></SelectTrigger><SelectContent><SelectItem value="balanced">Uso equilibrado</SelectItem><SelectItem value="games">Jogos</SelectItem><SelectItem value="work">Trabalho e criação</SelectItem></SelectContent></Select></div><label className="block text-sm">Programas e jogos<Input className="lab-input mt-2" placeholder="Ex.: AutoCAD, SketchUp, Valorant" value={details.applications ?? ""} maxLength={300} onChange={e => setDetails({ ...details, applications: e.target.value })} /></label><label className="block text-sm">Observações<Textarea className="lab-input mt-2 min-h-28" value={details.notes} maxLength={3000} onChange={e => setDetails({ ...details, notes: e.target.value })} /></label>{details.isExample && <Button variant="outline" className={secondary} onClick={() => setDetails({ ...details, isExample: false })}>Já adaptei o exemplo para o meu PC</Button>}</div>}<DialogFooter><Button variant="outline" className={secondary} onClick={() => setDetails(null)}>Cancelar</Button><Button className={primary} disabled={!details?.name.trim()} onClick={() => { if (details) onChange(details); setDetails(null); }}>Aplicar à edição</Button></DialogFooter></DialogContent></Dialog>
    <Dialog open={!!confirmation} onOpenChange={open => !open && setConfirmation(null)}><DialogContent className="border-white/10 bg-[#0c1320] text-slate-100"><DialogHeader><DialogTitle>{confirmation?.title}</DialogTitle><DialogDescription className="leading-6 text-slate-400">{confirmation?.detail}</DialogDescription></DialogHeader><DialogFooter><Button variant="outline" className={secondary} onClick={() => setConfirmation(null)}>Cancelar</Button><Button className={primary} onClick={() => { confirmation?.action(); setConfirmation(null); }}>Confirmar</Button></DialogFooter></DialogContent></Dialog>
  </div>;
}

function names(build: BuildConfig, category: PartCategory, parts: Part[]) { return build.parts[category]?.map(id => parts.find(p => p.id === id)?.name ?? `Modelo ${id}`).join(" + ") || "Não informado"; }

function CheckList({ checks, onTerm, compact = false }: { checks: PcCheck[]; onTerm: (id: string) => void; compact?: boolean }) {
  const order = { attention: 0, pending: 1, ok: 2 };
  return <div className={`grid gap-3 ${compact ? "" : "lg:grid-cols-2"}`}>{[...checks].sort((a, b) => order[a.status] - order[b.status]).map(check => {
    const Icon = check.status === "ok" ? CircleCheck : check.status === "attention" ? CircleAlert : CircleHelp;
    const color = check.status === "ok" ? "text-emerald-300" : check.status === "attention" ? "text-amber-300" : "text-slate-400";
    return <article key={check.id} className="lab-panel p-5"><div className="flex items-center gap-2"><Icon className={`size-4 ${color}`} /><span className={`text-xs font-semibold uppercase tracking-wide ${color}`}>{check.status === "ok" ? "Confere" : check.status === "attention" ? "Atenção" : "Por verificar"}</span>{check.term && <button onClick={() => onTerm(check.term!)} className="ml-auto rounded p-1 text-slate-400 hover:text-cyan-200" aria-label={`Entender ${check.term}`}><CircleHelp className="size-4" /></button>}</div><h4 className="mt-3 font-semibold">{check.title}</h4><p className="mt-2 text-sm leading-6 text-slate-400">{check.detail}</p></article>;
  })}</div>;
}

function PartPicker({ picker, parts, selected, onClose, onSelect, onCustom, onTerm }: { picker: Picker | null; parts: Part[]; selected?: string; onClose: () => void; onSelect: (part: Part) => void; onCustom: () => void; onTerm: (id: string) => void }) {
  const [query, setQuery] = useState("");
  const matches = picker ? parts.filter(p => p.category === picker.category && `${p.brand} ${p.name} ${p.platform ?? ""}`.toLocaleLowerCase("pt-BR").includes(query.toLocaleLowerCase("pt-BR"))) : [];
  return <Sheet open={!!picker} onOpenChange={open => { if (!open) { onClose(); setQuery(""); } }}><SheetContent showCloseButton={false} className="w-full gap-0 border-white/10 bg-[#0c1320] text-slate-100 sm:max-w-xl"><SheetHeader className="border-b border-white/10 p-6 pr-14"><SheetTitle>{picker ? categoryMeta[picker.category].label : "Escolher peça"}</SheetTitle><SheetDescription className="leading-6 text-slate-400">{picker?.simulation ? "Escolha uma peça para a simulação." : "Escolha o modelo exato instalado no seu PC."} As especificações vêm do catálogo e podem estar incompletas.</SheetDescription></SheetHeader><SheetClose className="absolute right-5 top-5 rounded p-1 text-slate-400" aria-label="Fechar seleção"><X className="size-5" /></SheetClose><div className="p-5"><div className="relative"><Search className="absolute left-3 top-3 size-4 text-slate-500" /><Input className="lab-input h-11 pl-10" value={query} onChange={e => setQuery(e.target.value)} aria-label="Buscar modelo ou fabricante" placeholder="Buscar modelo ou fabricante" /></div><p className="mt-2 text-sm text-slate-500" role="status">{matches.length} modelos encontrados</p></div><div className="min-h-0 flex-1 space-y-3 overflow-y-auto px-5 pb-5">{matches.map(part => <article key={part.id} className={`rounded-xl border p-4 ${part.id === selected ? "border-cyan-300/30 bg-cyan-300/5" : "border-white/10 bg-black/15"}`}><div className="text-xs font-semibold uppercase tracking-wide text-cyan-300">{part.brand}{part.tags.includes("personalizada") ? " · pessoal" : ""}</div><h4 className="mt-1 font-bold">{part.name}</h4><dl className="my-3 grid grid-cols-2 gap-3">{compareMetrics[part.category].slice(0, 4).map(metric => <div key={metric.key}><dt className="flex items-center gap-1 text-xs text-slate-500">{metric.label}{metric.termId && <button aria-label={`O que é ${metric.label}?`} onClick={() => onTerm(metric.termId!)}><CircleHelp className="size-3" /></button>}</dt><dd className="mt-1 text-sm">{formatSpecValue(part.specs[metric.key], metric.unit)}</dd></div>)}</dl><Button className={`w-full ${part.id === selected ? secondary : primary}`} variant={part.id === selected ? "outline" : "default"} disabled={part.id === selected} onClick={() => { onSelect(part); setQuery(""); }}>{part.id === selected ? "Selecionada neste slot" : picker?.simulation ? "Usar na simulação" : "Adicionar ao Meu PC"}{part.id !== selected && <ArrowRight />}</Button></article>)}{!matches.length && <p className="py-8 text-center text-slate-400">Nenhum modelo com esse nome. Tente outro termo.</p>}</div>{!picker?.simulation && <div className="border-t border-white/10 p-5"><Button variant="outline" className={`w-full ${secondary}`} onClick={() => { setQuery(""); onCustom(); }}><Plus />Meu modelo não está aqui</Button></div>}</SheetContent></Sheet>;
}
