"use client";

import { useMemo, useState } from "react";
import { ArrowRight, BookOpen, FilterX, PackagePlus, Search, SquareStack } from "lucide-react";
import { categoryMeta } from "@/app/data/catalog";
import { productMediaFor } from "@/app/data/product-media";
import { compareMetrics } from "@/app/data/glossary";
import { formatSpecValue } from "@/app/lib/compatibility";
import { partIdentity, usageTags } from "@/app/lib/part-insights";
import { partCategories, type Part, type PartCategory } from "@/app/lib/types";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Dialog, DialogContent, DialogDescription, DialogHeader, DialogTitle } from "@/components/ui/dialog";

const money = (n: number) => n.toLocaleString("pt-BR", { style: "currency", currency: "BRL", maximumFractionDigits: 0 });
export function CatalogFiltersSelect({ label, value, options, onChange }: { label: string; value: string; options: { value: string; label: string }[]; onChange: (v: string) => void }) {
  return <div><span className="mb-2 block text-sm text-slate-400">{label}</span><Select value={value} onValueChange={onChange}><SelectTrigger aria-label={label} className="lab-input h-10 w-full"><SelectValue /></SelectTrigger><SelectContent className="max-h-80">{options.map(o => <SelectItem key={o.value} value={o.value}>{o.label}</SelectItem>)}</SelectContent></Select></div>;
}
const choices = (values: string[], all: string) => [{ value: "all", label: all }, ...[...new Set(values)].sort().map(value => ({ value, label: value }))];

export function PartCatalog({ parts, publicMode = false, onUse, onAddCustom, onTerm }: { parts: Part[]; publicMode?: boolean; onUse: (part: Part) => void; onAddCustom: () => void; onTerm: (id: string) => void }) {
  const [category, setCategory] = useState<PartCategory | "all">("all");
  const [query, setQuery] = useState("");
  const [brand, setBrand] = useState("all"), [chip, setChip] = useState("all"), [socket, setSocket] = useState("all");
  const [vram, setVram] = useState("all"), [use, setUse] = useState("all"), [quality, setQuality] = useState("all"), [price, setPrice] = useState("");
  const [custom, setCustom] = useState<Part | null>(null);
  const [failedImages, setFailedImages] = useState<string[]>([]);
  const categoryParts = useMemo(() => parts.filter(p => category === "all" || p.category === category), [parts, category]);
  const shown = categoryParts.filter(p => (brand === "all" || p.brand === brand) && (chip === "all" || p.specs.gpuVendor === chip) && (socket === "all" || p.specs.socket === socket) && (vram === "all" || (typeof p.specs.vram === "number" && p.specs.vram >= Number(vram))) && (use === "all" || usageTags(p).includes(use)) && (quality === "all" || p.quality === quality) && (!price || (p.price > 0 && p.price <= Number(price))) && `${p.name} ${p.brand} ${p.tags.join(" ")} ${p.platform ?? ""}`.toLocaleLowerCase("pt-BR").includes(query.toLocaleLowerCase("pt-BR")));
  function reset() { setQuery(""); setBrand("all"); setChip("all"); setSocket("all"); setVram("all"); setUse("all"); setQuality("all"); setPrice(""); }
  return <div className="space-y-5">
    <section className="lab-panel p-4 sm:p-5"><div className="flex flex-wrap gap-3"><div className="relative min-w-52 flex-1"><Search className="absolute left-3 top-3 size-4 text-slate-500" /><Input className="lab-input h-11 pl-10" aria-label="Buscar peças" placeholder="Modelo, fabricante ou característica…" value={query} onChange={e => setQuery(e.target.value)} /></div>{!publicMode && <Button className="h-11 bg-cyan-300 text-slate-950" onClick={onAddCustom}><PackagePlus />Cadastrar peça</Button>}</div>
      <div className="my-4 flex gap-2 overflow-x-auto pb-2" aria-label="Categorias">{[{ id: "all", label: "Todas" }, ...partCategories.map(id => ({ id, label: categoryMeta[id].short }))].map(c => <button key={c.id} aria-pressed={category === c.id} onClick={() => { setCategory(c.id as PartCategory | "all"); setBrand("all"); setChip("all"); setSocket("all"); setVram("all"); }} className={`filter-chip ${category === c.id ? "active" : ""}`}>{c.label}</button>)}</div>
      <div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4"><CatalogFiltersSelect label={category === "gpu" ? "Marca da placa" : "Marca / fabricante"} value={brand} onChange={setBrand} options={choices(categoryParts.map(p => p.brand), "Todas as marcas")} /><CatalogFiltersSelect label="Tipo de uso" value={use} onChange={setUse} options={choices(parts.flatMap(usageTags), "Todos os usos")} />{category === "gpu" ? <><CatalogFiltersSelect label="Fabricante do chip" value={chip} onChange={setChip} options={choices(categoryParts.map(p => String(p.specs.gpuVendor ?? "Não informado")), "Todos os chips")} /><CatalogFiltersSelect label="VRAM mínima" value={vram} onChange={setVram} options={[{ value: "all", label: "Qualquer capacidade" }, ...[4, 8, 12, 16, 24].map(n => ({ value: String(n), label: `${n} GB ou mais` }))]} /><CatalogFiltersSelect label="Avaliação do catálogo" value={quality} onChange={setQuality} options={choices(parts.map(p => p.quality), "Todas as avaliações")} /></> : <><CatalogFiltersSelect label="Plataforma / socket" value={socket} onChange={setSocket} options={choices(categoryParts.flatMap(p => typeof p.specs.socket === "string" ? [p.specs.socket] : []), "Todas as plataformas")} /><CatalogFiltersSelect label="Avaliação do catálogo" value={quality} onChange={setQuality} options={choices(parts.map(p => p.quality), "Todas as avaliações")} /></>}</div>
      <div className="mt-4 flex flex-wrap items-end gap-4"><label className="block text-sm text-slate-400">Preço de referência até (R$)<Input type="number" min="1" className="lab-input mt-2 w-48" placeholder="Sem limite" value={price} onChange={e => setPrice(e.target.value)} /></label><p className="max-w-lg flex-1 text-sm leading-6 text-slate-500">Referências do catálogo, sem cotação ao vivo.{price ? " Peças sem preço ficam fora deste filtro." : " Filtros de uso indicam contextos para avaliar, não desempenho garantido."}</p><Button variant="ghost" onClick={reset}><FilterX />Limpar filtros</Button></div>
    </section>
    <div className="flex items-center justify-between text-sm text-slate-400" role="status"><span>{shown.length} de {categoryParts.length} peças</span><span>Abra a ficha para entender o modelo</span></div>
    <div className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">{shown.map(part => {
      const identity = partIdentity(part);
      const media = productMediaFor(part);
      const imageAvailable = !!media && !failedImages.includes(part.id);
      return <article className="lab-panel flex flex-col p-5" key={part.id}><div className="flex items-center justify-between gap-2 text-xs"><span className="font-semibold uppercase tracking-wide text-cyan-300">{part.brand} · {categoryMeta[part.category].short}</span><span className="text-slate-500">{part.source ? "Fonte vinculada" : "Ficha em validação"}</span></div><div className="mt-3 flex h-44 items-center justify-center overflow-hidden rounded-xl bg-white p-4">{imageAvailable ? <img src={media.imageUrl} alt={media.alt} loading="lazy" decoding="async" referrerPolicy="no-referrer" className="h-full w-full object-contain" onError={() => setFailedImages(current => current.includes(part.id) ? current : [...current, part.id])} /> : <div className="text-center text-sm text-slate-500"><BookOpen className="mx-auto mb-2 size-8" /><span>Imagem do modelo ainda não verificada</span></div>}</div><h3 className="mt-3 text-xl font-bold">{part.name}</h3>{part.category === "gpu" && <p className="mt-2 text-sm text-slate-400">Chip {identity.vendor} {identity.chip} · {identity.isModel ? "modelo identificado" : "variante a confirmar"}</p>}<p className="mt-3 text-sm leading-6 text-slate-400">{part.summary}</p><dl className="my-4 grid grid-cols-2 gap-3 border-y border-white/8 py-4">{compareMetrics[part.category].slice(0, 4).map(metric => <div key={metric.key}><dt className="text-sm text-slate-500">{metric.termId ? <button className="text-left underline decoration-dotted underline-offset-4" onClick={() => onTerm(metric.termId!)}>{metric.label}</button> : metric.label}</dt><dd className="mt-1 font-medium">{formatSpecValue(part.specs[metric.key], metric.unit)}</dd></div>)}</dl><p className="mb-4 text-sm text-slate-400">{usageTags(part).join(" · ")}</p>{(part.specs.tdp || part.specs.tgp || (part.category === "psu" && part.specs.wattage)) && <p className="mb-4 text-sm text-slate-400">{part.category === "cpu" ? `TDP informado: ${part.specs.tdp} W (referência térmica)` : part.category === "gpu" ? `Potência da GPU informada: ${part.specs.tgp} W` : `Potência nominal: ${part.specs.wattage} W`}</p>}<div className="mt-auto"><div className="mb-4 flex items-center justify-between gap-2"><span className="text-sm text-slate-500">Referência estimada</span><strong>{part.price > 0 ? money(part.price) : "Sem preço"}</strong></div><div className="grid grid-cols-2 gap-2">{part.id.startsWith("custom-") ? <Button variant="outline" className="border-white/10 bg-white/5" onClick={() => setCustom(part)}><BookOpen />Ver ficha</Button> : <Button variant="outline" className="border-white/10 bg-white/5" asChild><a href={`/pecas/${encodeURIComponent(part.id)}`}><BookOpen />Ver peça</a></Button>}<Button className="bg-cyan-300 text-slate-950 hover:bg-cyan-200" onClick={() => onUse(part)}>{publicMode ? <SquareStack /> : <ArrowRight />}{publicMode ? "Comparar" : "Usar"}</Button></div></div></article>;
    })}</div>
    {!shown.length && <div className="lab-panel p-8 text-center"><h3 className="text-xl font-bold">Nenhuma peça com esses filtros</h3><p className="mt-2 text-slate-400">Tente outra marca, remova um filtro ou ajuste a busca.</p><Button variant="outline" className="mt-5" onClick={reset}>Limpar filtros</Button></div>}
    <Dialog open={!!custom} onOpenChange={open => !open && setCustom(null)}><DialogContent className="max-h-[85dvh] overflow-y-auto"><DialogHeader><DialogTitle>{custom?.name}</DialogTitle><DialogDescription>Ficha pessoal · dados informados por você, disponíveis na sua conta.</DialogDescription></DialogHeader>{custom && <><p className="leading-7 text-slate-400">{custom.summary}</p><dl className="space-y-3">{compareMetrics[custom.category].map(m => <div key={m.key} className="flex justify-between gap-4 border-b border-white/10 pb-2"><dt className="text-slate-400">{m.label}</dt><dd>{formatSpecValue(custom.specs[m.key], m.unit)}</dd></div>)}</dl><Button onClick={() => { onUse(custom); setCustom(null); }}>Usar no montador</Button></>}</DialogContent></Dialog>
  </div>;
}
