import { ArrowLeft, Download, FileJson, Monitor, ShieldCheck, Upload } from "lucide-react";
import { Button } from "@/components/ui/button";

export const metadata = { title: "UpgradePC Detector — Importar o hardware do Windows" };
export default function DetectorPage() {
  return <main className="mx-auto max-w-5xl space-y-6 px-4 py-8 sm:px-8"><a href="/meu-pc" className="flex items-center gap-2 text-sm text-slate-400"><ArrowLeft className="size-4" />Voltar ao Meu PC</a><section className="lab-panel p-6 sm:p-8"><div className="flex items-center gap-2 text-sm text-cyan-200"><Monitor className="size-5" />Windows 10 / 11 · 64 bits · versão 1.0.0</div><h1 className="mt-4 text-3xl font-bold sm:text-4xl">UpgradePC Detector</h1><p className="mt-4 max-w-3xl text-base leading-7 text-slate-400">Identifique o hardware do seu computador e leve os dados para o Meu PC. Você revisa o relatório, confirma os modelos e escolhe o que quer guardar.</p><div className="mt-6 flex flex-wrap gap-3"><Button asChild className="bg-cyan-300 text-slate-950 hover:bg-cyan-200"><a href="/downloads/UpgradePC-Detector.exe" download><Download />Baixar Detector (.exe)</a></Button><Button asChild variant="outline"><a href="/meu-pc?import=detector"><Upload />Já tenho o arquivo JSON</a></Button></div><p className="mt-4 text-sm leading-6 text-slate-400">Versão inicial sem assinatura digital. O Windows pode identificar o editor como desconhecido. A leitura real do hardware e a interface ainda precisam de validação em uma máquina Windows. O cadastro manual continua disponível.</p></section>
    <section className="grid gap-4 md:grid-cols-3">{[["01", "Execute no Windows", "Abra o Detector e clique em Detectar hardware. Não é necessário instalar um serviço ou entrar na sua conta."], ["02", "Revise e salve", "Veja o relatório completo e salve upgradepc-config.json em uma pasta de sua escolha."], ["03", "Importe no Meu PC", "Selecione ou arraste o JSON, confirme os modelos e aplique à edição. Depois clique em Salvar para guardar na conta."]].map(([n, title, body]) => <article key={n} className="lab-panel p-5"><span className="text-sm font-bold text-cyan-200">{n}</span><h2 className="mt-3 text-lg font-bold">{title}</h2><p className="mt-3 text-sm leading-6 text-slate-400">{body}</p></article>)}</section>
    <div className="grid gap-5 md:grid-cols-2"><section className="lab-panel p-6"><h2 className="flex items-center gap-2 text-lg font-bold"><FileJson className="size-5 text-cyan-300" />O que é identificado</h2><p className="mt-4 leading-7 text-slate-300">CPU, placa-mãe, adaptadores de vídeo, módulos de RAM, discos e monitores ativos, conforme os dados fornecidos pelo Windows.</p><p className="mt-3 text-sm leading-6 text-slate-400">A variante da GPU, VRAM, resolução e Hz do monitor podem precisar de confirmação. Fonte, cooler e gabinete permanecem manuais. Discos externos ou virtuais podem aparecer e devem ser excluídos da importação quando não fizerem parte do PC.</p></section><section className="lab-panel p-6"><h2 className="flex items-center gap-2 text-lg font-bold"><ShieldCheck className="size-5 text-cyan-300" />Você controla o relatório</h2><p className="mt-4 leading-7 text-slate-300">A consulta é local. O Detector não envia dados, não pede senha e não coleta documentos, nomes de usuário ou números de série.</p><p className="mt-3 text-sm leading-6 text-slate-400">Os dados só entram na conta após a revisão no site e o salvamento. O programa não altera BIOS, drivers ou configurações do Windows.</p></section></div>
    <details className="rounded-xl border border-white/10 p-5"><summary className="cursor-pointer font-semibold">Detalhes do download e limitações</summary><div className="mt-4 space-y-3 text-sm leading-6 text-slate-400"><p>Requer Windows PowerShell e os provedores CIM/WMI do Windows. Se a execução for bloqueada por políticas do computador, use o cadastro manual ou procure o administrador. A ausência de um dado não significa ausência da peça.</p><p><a className="text-cyan-200 underline" href="/downloads/UpgradePC-Detector.sha256.txt" download>Checksum SHA-256</a> · <a className="text-cyan-200 underline" href="/downloads/UpgradePC-Detector.ps1" download>Código legível da consulta</a></p><p>Fontes técnicas: <a className="text-cyan-200 underline" href="https://learn.microsoft.com/en-us/windows/win32/cimwin32prov/win32-physicalmemory" target="_blank" rel="noopener noreferrer">RAM no Windows</a>, <a className="text-cyan-200 underline" href="https://learn.microsoft.com/en-us/windows/win32/cimwin32prov/win32-videocontroller" target="_blank" rel="noopener noreferrer">adaptadores de vídeo</a> e <a className="text-cyan-200 underline" href="https://learn.microsoft.com/en-us/windows/win32/wmicoreprov/wmimonitorid" target="_blank" rel="noopener noreferrer">identificação de monitores</a>.</p></div></details>
  </main>;
}
